[package]
name = "matrixmultiply-test"
version = "0.1.0"
authors = ["Violeta Hernández <eric.ivan.hdz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.25.4"
rand = "0.8.3"