name: Rust Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false 
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: 1

    steps:
      - uses: actions/checkout@v2
      
      - name: Build & run tests
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test && cargo run
